### ISSUE TITLE
Add a 404 page that redirects to welcome.html…

### ISSUE THREAD

**Issue by bwinton** [bwinton/StyleGuide#21]
So that https://bwinton.github.io/StyleGuide/bad.html#worse goes somewhere better than it currently does.  :wink:

**Comment by aminalhazwani** [comment]
@bwinton what are the advantages of having a redirect instead of a 404? i have no data but talking from experience the 404 page is a much more established pattern. If we think about in terms of clicks it would be the same. One click to go from the 404 page to the welcome page (we can even have the toc in the 404). And one click on the notification with automatic redirect to the welcome page (I would add a dismiss button on the notification in order to make sure that the users is aware of what just happaned).

**Comment by bwinton** [comment]
We don't have a 404, and we would like people to land on a page that makes sense, particularly if we're messing with the urls (as we are once this fork gets merged to the real repo)…

It might make more sense to see if we can translate something like `https://firefoxux.github.io/StyleGuide/#/typography` to `https://firefoxux.github.io/StyleGuide/typography.html`, so that old links just work, but that would be a more involved change.

If you wanted to add a custom 404 page, I guess that wouldn't be so bad, but why not save people a click and just redirect them?
